# Generated by Django 5.1.6 on 2025-04-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_usersignup_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignup',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='photo',
            field=models.ImageField(upload_to='Photos'),
        ),
    ]
